export const ERROR_CODES = Object.freeze({
  MISSING_FIELDS: "MISSING_FIELDS",
  WRONG_CREDENTIALS: "WRONG_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  COOKIES_NOT_FOUND: "COOKIES_NOT_FOUND",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  NOT_FOUND: "NOT_FOUND",
});
